services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    environment:
      STORAGE_BACKEND: local
      CORS_ORIGINS: http://localhost
    ports:
      - "127.0.0.1:8000:8000"
    labels:
      app: "the-yields"
      service: "backend"
  ui:
    build:
      context: ./ui
    env_file:
      - ./ui/.env
    ports:
      - "127.0.0.1:3000:8080"
    depends_on:
      - backend
    labels:
      app: "the-yields"
      service: "ui"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - --nginx.scrape-uri=http://ui/stub_status
    ports:
      - "127.0.0.1:9113:9113"
    depends_on:
      - ui
    labels:
      app: "the-yields"
      service: "nginx-exporter"
