---
- name: Create fail2ban local config
  copy:
    content: |
      [DEFAULT]
      bantime = {{ fail2ban_bantime }}
      findtime = {{ fail2ban_findtime }}
      maxretry = {{ fail2ban_maxretry }}
      destemail = {{ admin_email }}
      sendername = Fail2Ban
      action = %(action_mwl)s

      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log

      [sshd-ddos]
      enabled = true
      port = ssh
      filter = sshd-ddos
      logpath = /var/log/auth.log
      maxretry = 10
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: restart fail2ban

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: Show fail2ban status
  command: fail2ban-client status
  register: fail2ban_status
  changed_when: false

- name: Print fail2ban status
  debug:
    var: fail2ban_status.stdout_lines
