---
- name: Reset UFW to defaults
  ufw:
    state: reset

- name: Set UFW default deny incoming
  ufw:
    direction: incoming
    policy: deny

- name: Set UFW default allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp
    comment: "Allow SSH"

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"
    proto: tcp
    comment: "Allow HTTP"

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"
    proto: tcp
    comment: "Allow HTTPS"

- name: Enable UFW
  ufw:
    state: enabled

- name: Show UFW status
  command: ufw status
  register: ufw_status
  changed_when: false

- name: Print UFW status
  debug:
    var: ufw_status.stdout_lines
