"""initial schema

Revision ID: 938beee1a35d
Revises:
Create Date: 2026-03-20 19:51:31.054289+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "938beee1a35d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "sub",
            sa.String(length=128),
            nullable=False,
            comment="Cognito identity sub (stable unique identifier)",
        ),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_sub"), "users", ["sub"], unique=True)
    op.create_table(
        "depots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment='Display name, e.g. "TradeRepublic" or "Interactive Brokers"',
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_depot_user_name"),
    )
    op.create_index(op.f("ix_depots_user_id"), "depots", ["user_id"], unique=False)
    op.create_table(
        "year_goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "dividend_goal",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
            comment="Target annual dividend income",
        ),
        sa.Column(
            "yield_goal",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
            comment="Target annual yield/interest income",
        ),
        sa.Column(
            "steuerfreibetrag",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
            comment="German tax-free savings allowance for the year",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "year", name="uq_year_goal_user_year"),
    )
    op.create_index(
        op.f("ix_year_goals_user_id"), "year_goals", ["user_id"], unique=False
    )
    op.create_table(
        "dividend_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("depot_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "ticker",
            sa.String(length=100),
            nullable=False,
            comment="User-defined unique key within the depot+year,"
            "typically a ticker symbol",
        ),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment="Free-text display name, e.g. 'Apple Inc.'",
        ),
        sa.ForeignKeyConstraint(["depot_id"], ["depots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "depot_id", "year", "ticker", name="uq_dividend_depot_year_ticker"
        ),
    )
    op.create_index(
        op.f("ix_dividend_entries_depot_id"),
        "dividend_entries",
        ["depot_id"],
        unique=False,
    )
    op.create_table(
        "yield_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("depot_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "account_key",
            sa.String(length=200),
            nullable=False,
            comment="User-defined label, used as both key and display name",
        ),
        sa.ForeignKeyConstraint(["depot_id"], ["depots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "depot_id", "year", "account_key", name="uq_yield_depot_year_account"
        ),
    )
    op.create_index(
        op.f("ix_yield_entries_depot_id"), "yield_entries", ["depot_id"], unique=False
    )
    op.create_table(
        "dividend_months",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False, comment="Calendar month 1–12"),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="Dividend income in user's currency",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["dividend_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "month", name="uq_dividend_entry_month"),
    )
    op.create_index(
        op.f("ix_dividend_months_entry_id"),
        "dividend_months",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "yield_months",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False, comment="Calendar month 1–12"),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="Yield/interest income in user's currency",
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["yield_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "month", name="uq_yield_entry_month"),
    )
    op.create_index(
        op.f("ix_yield_months_entry_id"), "yield_months", ["entry_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_yield_months_entry_id"), table_name="yield_months")
    op.drop_table("yield_months")
    op.drop_index(op.f("ix_dividend_months_entry_id"), table_name="dividend_months")
    op.drop_table("dividend_months")
    op.drop_index(op.f("ix_yield_entries_depot_id"), table_name="yield_entries")
    op.drop_table("yield_entries")
    op.drop_index(op.f("ix_dividend_entries_depot_id"), table_name="dividend_entries")
    op.drop_table("dividend_entries")
    op.drop_index(op.f("ix_year_goals_user_id"), table_name="year_goals")
    op.drop_table("year_goals")
    op.drop_index(op.f("ix_depots_user_id"), table_name="depots")
    op.drop_table("depots")
    op.drop_index(op.f("ix_users_sub"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
